format = '[Ty](bold green)[@](bold red)[NixOS](bold blue)[:](bold red)$directory$git_branch${custom.jj-}${custom.jj}$git_status$nix_shell$package$python$rust[\]](bold green)[†](bold red) $character$status'

scan_timeout = 0
command_timeout = 0
add_newline = false

[character]
success_symbol = "[❯](bold blue) "
error_symbol = "[❯](bold red) "
disabled = false

[directory]
style = "bold yellow"
truncation_length = 3
fish_style_pwd_dir_length = 1

# Git branch appearance
[git_branch]
disabled = true
only_attached = false
symbol = ""
style = "bold purple"
format = "on [$symbol$branch]($style) "

[custom.jj]
command = '''jj log -r @ --no-graph -T 'local_bookmarks.join(", ")''''
detect_folders = [".jj"]
symbol = ""
style = "bold purple"
format = "on [$symbol$output]($style) "
when = "test -d .jj"
disabled = false
ignore_timeout = true

[status]
disabled = false
format = '[\[$int\]](bold red) '
