format = '[Ty](bold green)[@](bold red)[NixOS](bold blue)[:](bold red)$directory$vcsh$fossil_branch$fossil_summary$git_state$git_metrics$git_branch${custom.jj-}${custom.jj}$git_commit$git_status$nix_shell$hg_branch$pijul_channel$docker_context$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam$golang$guix_shell$haskell$haxe$java$julia$kotlin$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$quarto$raku$rlang$red$ruby$rust$scala$solidity$spM$swift$terraform$typst$v$vagrant$vlang$zig$buf$nix_shell$conda$meson$spack$aws$gcloud$openstack$azure$crystal[\]](bold green)[†](bold red) $character'

right_format = "$os$shell$cmd_duration$jobs$memory_usage$status"

scan_timeout = 0
command_timeout = 0
add_newline = false

[character]
success_symbol = "[❯](bold blue) "
error_symbol = "[❯](bold red) "
disabled = false

[directory]
style = "bold yellow"
truncation_length = 3
fish_style_pwd_dir_length = 1

[os]
disabled = false
symbols = { NixOS = "❄ " }
style = "bold blue"
format = "[$symbol]($style)"

# Git branch appearance
[git_branch]
disabled = true
only_attached = false
symbol = ""
style = "bold purple"
format = "on [$symbol$branch]($style) "

[custom.jj]
command = '''jj log -r @ --no-graph -T 'local_bookmarks.join(", ")''''
detect_folders = [".jj"]
symbol = ""
style = "bold purple"
format = "on [$symbol$output]($style) "
when = "test -d .jj"
disabled = false
ignore_timeout = true

[shell]
disabled = false
style = "cyan bold"
format = "[$indicator]($style) "

[status]
disabled = false
format = '[\[$int\]](bold red) '

[memory_usage]
disabled = false
format = "[$symbol $ram $swap]($style)"
threshold = -1
style = "white bold dimmed"
symbol = "󰍛 "

[env_var]
disabled = false
format = "[$env_value]($style) "
style = "black bold"

[shlvl]
disabled = false
format = "[$symbol$shlvl]($style) "
threshold = 2
style = "cyan bold"
symbol = " "

[localip]
disabled = false
format = "[$localipv4]($style) "
ssh_only = true
style = "red bold"

[container]
disabled = false
format = "[$symbol[$name]]($style) "
style = "red bold"
symbol = "⬢ "

[kubernetes]
disabled = false
format = "[$symbol$context( ($namespace))]($style) "
style = "cyan bold"
symbol = "󱃾 "

[docker_context]
disabled = false
format = "[$symbol$context]($style) "
style = "blue bold"
symbol = " "

[vagrant]
disabled = false
format = "[$symbol$version]($style) "
style = "cyan bold"
symbol = "󰒍 "

[aws]
disabled = false
format = "[$symbol($profile)(\\($region\\))]($style) "
style = "orange bold"
symbol = " "

[gcloud]
disabled = false
format = "[$symbol($account)(\\($project\\))]($style) "
style = "blue bold"
symbol = "󱇊 "

[azure]
disabled = false
format = "[$symbol($subscription)]($style) "
style = "blue bold"
symbol = "󰠅 "

[openstack]
disabled = false
format = "[$symbol$cloud(\\($project\\))]($style) "
style = "violet bold"
symbol = "󰜉 "

[pulumi]
disabled = false
format = "[$symbol($stack)]($style) "
style = "orange bold"
symbol = " "

[vcsh]
disabled = false
format = "[$symbol$clone]($style) "
style = "yellow bold"
symbol = " "

[fossil_branch]
disabled = false
format = "[$symbol$branch]($style) "
style = "purple bold"
symbol = " "

[pijul_channel]
disabled = false
format = "[$symbol$channel]($style) "
style = "purple bold"
symbol = " "
